### ISSUE TITLE
Documentation/Readme: Video Unavailable

### ISSUE THREAD

**Issue by Normanras** [piersolenski/wtf.nvim#13]
Super minor, but just letting you know that both of the videos in the readme aren't working. The thumbnail appears and I can click play, but nothing happens. If I click the download button (three dots > download video) my browerser gives me the error of `Video unavailable for download`. 

Here's the video src:
* Full URL `https://private-user-images.githubusercontent.com/1285419/265102089-7572b101-664c-4069-aa45-84adc2678e25.mp4?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4Nzc0MjYsIm5iZiI6MTcwMTg3NzEyNiwicGF0aCI6Ii8xMjg1NDE5LzI2NTEwMjA4OS03NTcyYjEwMS02NjRjLTQwNjktYWE0NS04NGFkYzI2NzhlMjUubXA0P1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDZUMTUzODQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDM3MTA2OTE1MTI2ZjBiMWEzZTBjMzM2NjQzNGM2YTljZjM1NTFjMWNiNGVhNjQzZTVmZmIwOWExYjZjNDgzNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ZC5imJChUH_L_GMHRof_2EQKimBNs2xxhfe1BLthTNM` 
* URL without JWT: `https://private-user-images.githubusercontent.com/1285419/265102089-7572b101-664c-4069-aa45-84adc2678e25.mp4`

Both links return a 404. Thanks for the neat plugin!

**Comment by piersolenski** [comment]
I'm afraid I can't replicate this in a private window in Chrome, which browser are you using?

**Comment by Normanras** [comment]
Weird. Just a regular window in Chrome. I just tried in incognito and it worked, but not in my normal/profiled window. 

Just cleared my cache and it works again... very odd. Ignore the non-issue!
