### ISSUE TITLE
WtfSearch doesn't support Windows

### ISSUE THREAD

**Issue by comiluv** [piersolenski/wtf.nvim#14]
In Windows 11, with cursor on a diagnostic message, `:WtfSearch google` opens a `cmd` window instead of opening system default web browser.
Screeenshot:
In Neovim,
<img width="610" alt="화면 캡처 2023-12-08 035442" src="https://github.com/piersolenski/wtf.nvim/assets/19642705/46eb36d8-2152-4d3d-8652-b2c0a049d5db">
<img width="735" alt="화면 캡처 2023-12-08 035335" src="https://github.com/piersolenski/wtf.nvim/assets/19642705/5e6e340d-61fa-4789-9453-151583436cfc">

**Comment by piersolenski** [comment]
Thanks for the PR!
