### ISSUE TITLE
History file naming scheme is incompatible with Windows

### ISSUE THREAD

**Issue by comiluv** [piersolenski/wtf.nvim#32]
Currently history files are to be named from timestamp formatted in ```"%Y-%m-%dT%H-%M-%S"```
But ```:``` character is forbidden in Windows file system. Being unable to create the history file when ```require"wtf".ai()``` is called, Neovim shows error messages saying unable to find the history file.
See [Microsoft Naming Conventions](https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions) for more info

**Comment by piersolenski** [comment]
Fixed in https://github.com/piersolenski/wtf.nvim/commit/d531326435bd3192cbc1b563300798d47c0ecdf5
